In [3]:
import numpy as np

np.random.seed(42)

A = np.random.randint(1, 11, size=(4, 3))
B = np.random.randint(1, 11, size=(3, 5))

print("Matrix A:")
print(A)
print("Shape:", A.shape)

print("\nMatrix B:")
print(B)
print("Shape:", B.shape)

assert A.shape[1] == B.shape[0]

C = np.dot(A, B)

print("\nMatrix C:")
print(C)
print("Shape:", C.shape)

print("\nTotal Sum:")
print(np.sum(C))

print("\nRow-wise Sum:")
print(np.sum(C, axis=1))

print("\nColumn-wise Sum:")
print(np.sum(C, axis=0))

Matrix A:
[[ 7  4  8]
 [ 5  7 10]
 [ 3  7  8]
 [ 5  4  8]]
Shape: (4, 3)

Matrix B:
[[ 8  3  6  5  2]
 [ 8  6  2  5  1]
 [10  6  9  1 10]]
Shape: (3, 5)

Matrix C:
[[168  93 122  63  98]
 [196 117 134  70 117]
 [160  99 104  58  93]
 [152  87 110  53  94]]
Shape: (4, 5)

Total Sum:
2188

Row-wise Sum:
[544 634 514 496]

Column-wise Sum:
[676 396 470 244 402]
