In [1]:
print("Shashwat")


Shashwat


In [3]:
import numpy as np

a = np.array([10,20,30])
print(np.mean(a))


20.0


In [4]:
import numpy as np

# ------------------
# Scalar
# ------------------
scalar = np.array(10)

print("Scalar:")
print(scalar)
print("Dimensions:", scalar.ndim)
print()

# ------------------
# Vector
# ------------------
vector = np.array([1, 2, 3, 4, 5])

print("Vector:")
print(vector)
print("Dimensions:", vector.ndim)
print()

# ------------------
# Matrix
# ------------------
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print("Matrix:")
print(matrix)
print("Dimensions:", matrix.ndim)
print()

# ------------------
# Operations
# ------------------

# Scalar multiplication
print("Vector × 2:")
print(vector * 2)
print()



print("Matrix Addition:")
print(matrix + matrix2)
print()

# Matrix multiplication
A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [5, 6],
    [7, 8]
])

print("Matrix Multiplication:")
print(np.matmul(A, B))

Scalar:
10
Dimensions: 0

Vector:
[1 2 3 4 5]
Dimensions: 1

Matrix:
[[1 2 3]
 [4 5 6]]
Dimensions: 2

Vector × 2:
[ 2  4  6  8 10]

Matrix Addition:


NameError: name 'matrix2' is not defined

In [5]:
import numpy as np

v = np.array([1, 2, 3])

print(v * 2)


[2 4 6]


In [6]:
import numpy as np

v = np.array([1, 2])
m = np.array([[3, 4],
              [5, 6]])

print(v @ m)


[13 16]


In [7]:
import numpy as np

# ------------------
# Scalar
# ------------------
scalar = np.array(10)

print("Scalar:")
print(scalar)
print("Dimensions:", scalar.ndim)
print()

# ------------------
# Vector
# ------------------
vector = np.array([1, 2, 3, 4, 5])

print("Vector:")
print(vector)
print("Dimensions:", vector.ndim)
print()

# ------------------
# Matrix
# ------------------
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print("Matrix:")
print(matrix)
print("Dimensions:", matrix.ndim)
print()

# ------------------
# Operations
# ------------------

# Scalar multiplication
print("Vector × 2:")
print(vector * 2)
print()

# Vector addition
vector2 = np.array([5, 4, 3, 2, 1])

print("Vector Addition:")
print(vector + vector2)
print()

# Matrix addition
matrix2 = np.array([
    [7, 8, 9],
    [10, 11, 12]
])

print("Matrix Addition:")
print(matrix + matrix2)
print()

# Matrix multiplication
A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [5, 6],
    [7, 8]
])

print("Matrix Multiplication:")
print(np.matmul(A, B))


Scalar:
10
Dimensions: 0

Vector:
[1 2 3 4 5]
Dimensions: 1

Matrix:
[[1 2 3]
 [4 5 6]]
Dimensions: 2

Vector × 2:
[ 2  4  6  8 10]

Vector Addition:
[6 6 6 6 6]

Matrix Addition:
[[ 8 10 12]
 [14 16 18]]

Matrix Multiplication:
[[19 22]
 [43 50]]


In [8]:
import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([[7, 8],
              [9, 10],
              [11, 12]])

C = A @ B

print(C)


[[ 58  64]
 [139 154]]


In [9]:
import numpy as np

# First Matrix (2 x 3)
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

# Second Matrix (3 x 4)
B = np.array([
    [7, 8, 9, 10],
    [11, 12, 13, 14],
    [15, 16, 17, 18]
])

print("Matrix A:")
print(A)

print("\nMatrix B:")
print(B)

print("\nShape of Matrix A:", A.shape)
print("Shape of Matrix B:", B.shape)

# Check if multiplication is possible
if A.shape[1] == B.shape[0]:
    result = np.matmul(A, B)

    print("\nResult of Matrix Multiplication:")
    print(result)

    print("\nShape of Result Matrix:", result.shape)
else:
    print("\nMatrix multiplication is not possible.")
    

Matrix A:
[[1 2 3]
 [4 5 6]]

Matrix B:
[[ 7  8  9 10]
 [11 12 13 14]
 [15 16 17 18]]

Shape of Matrix A: (2, 3)
Shape of Matrix B: (3, 4)

Result of Matrix Multiplication:
[[ 74  80  86  92]
 [173 188 203 218]]

Shape of Result Matrix: (2, 4)
